name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Show dependency file
      run: cat environment.yml
      
    - name: Install Mamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        cache-environment: true
        cache-downloads: true
        generate-run-shell: true

    - name: List environment
      run: |
        micromamba list
      shell: micromamba-shell {0}

    - name: Configure and compile the library
      run: |
        cmake -B build
        cmake --build build --parallel
      shell: micromamba-shell {0}

    - name: Run tests
      run: |
        ctest --output-on-failure --test-dir build
      shell: micromamba-shell {0}

    - name: Setup emscripten
      run: |
        emsdk update
        emsdk install 4.0.10

    - name: Configure and compile the project in web mode
      run: |
        emsdk activate 4.0.22
        EMSDK_PATH=$(python3 -c "import site; print(site.getsitepackages()[0])")/emsdk
        source "${EMSDK_PATH}/emsdk_env.sh"
        emcmake cmake -B build_web -DFA_BUILD_TESTS=ON -DFA_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
        cmake --build build_web --parallel
      shell: micromamba-shell {0}
